spring:
  profiles:
    active: local
  jpa:
    database:
      hibernate:
        ddl-auto: none
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/personnel}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: db/changelog/changelog.yml
    clear-checksums: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      add-mappings: false
  server:
    port: 8080
    error:
      whitelabel:
        enabled: true
  servlet:
    multipart:
      max-file-size: ${MP_MAX_FILE_SIZE:25MB}
      max-request-size: ${MP_MAX_REQUEST_SIZE:25MB}
  sql:
    init:
      encoding: UTF-8